/**
 * Slide relay for the Bible Presenter studio console.
 *
 * The console, the `/show` projector and the `/lower3rd` OBS Browser Source
 * all connect out to this Worker over `wss://` and exchange one JSON payload:
 * whatever the console last pushed. That replaces reaching *into* OBS with
 * obs-websocket, which only ever worked from the same machine — a phone can
 * publish here from any network, and an HTTPS page is allowed to open a
 * `wss://` socket from anywhere.
 *
 * Rooms are isolated by construction rather than by filtering. Each room name
 * addresses its own Durable Object instance, and Cloudflare guarantees exactly
 * one instance per name globally, so two churches running at the same time
 * hold their sockets in two different objects that cannot see each other's
 * memory. There is no shared connection list to get the filtering wrong on.
 *
 * The last payload is kept in the object's storage and replayed to every new
 * socket, so a Browser Source that starts — or reloads — mid-service draws the
 * current slide immediately instead of staying blank until the next push.
 */

/** Room names are generated by the client; anything else is a typo or a probe. */
const ROOM_PATTERN = /^[a-z0-9]{8,64}$/;

/** A slide with three translations is a few kB. This is room to spare. */
const MAX_MESSAGE_BYTES = 256 * 1024;

export class Room {
  constructor(state) {
    this.state = state;
  }

  async fetch(request) {
    if (request.headers.get('Upgrade') !== 'websocket') {
      return new Response('expected a websocket upgrade', { status: 426 });
    }

    const [client, server] = Object.values(new WebSocketPair());

    // The hibernation API, rather than `server.accept()`: a room sits idle
    // between slides, and hibernating sockets are not billed for duration.
    // Handlers arrive as the `webSocket*` methods below.
    this.state.acceptWebSocket(server);

    const last = await this.state.storage.get('last');

    if (last) {
      try {
        server.send(last);
      } catch (e) {
        // The socket died between accept and replay; nothing to do.
      }
    }

    return new Response(null, { status: 101, webSocket: client });
  }

  async webSocketMessage(sender, message) {
    if (typeof message !== 'string' || message.length > MAX_MESSAGE_BYTES) {
      return;
    }

    await this.state.storage.put('last', message);

    // Everyone but the sender: the console already knows what it just pushed,
    // and echoing would fight its own local state.
    for (const peer of this.state.getWebSockets()) {
      if (peer !== sender) {
        try {
          peer.send(message);
        } catch (e) {
          // A peer closing mid-broadcast must not stop the rest.
        }
      }
    }
  }

  async webSocketClose(ws, code, reason, wasClean) {
    try {
      ws.close(1000);
    } catch (e) {
      // Already gone.
    }
  }

  async webSocketError() {
    // Nothing to clean up: the runtime drops the socket for us.
  }
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === '/health') {
      return new Response('ok', { headers: { 'content-type': 'text/plain' } });
    }

    const room = url.pathname.replace(/^\/+/, '');

    if (!ROOM_PATTERN.test(room)) {
      return new Response('room must be 8-64 characters of a-z0-9', { status: 400 });
    }

    return env.ROOMS.get(env.ROOMS.idFromName(room)).fetch(request);
  },
};
