/**
 * Worker behind the Bible Presenter studio console. It does two jobs:
 *
 *   /<room>          a slide relay, one Durable Object per room
 *   /bible?...       a caching proxy in front of the holybible.ge API
 *
 * **The relay.** The console, the `/show` projector and the `/lower3rd` OBS
 * Browser Source all connect out here and exchange one JSON payload: whatever
 * the console last pushed. That replaces reaching *into* OBS with
 * obs-websocket, which only ever worked from the same machine — a phone can
 * publish here from any network, and an HTTPS page may open a `wss://` socket
 * from anywhere.
 *
 * Rooms are isolated by construction rather than by filtering. A room name
 * addresses its own Durable Object instance, and Cloudflare guarantees exactly
 * one instance per name globally, so two churches on air at once hold their
 * sockets in two objects that cannot see each other's memory.
 *
 * **The proxy.** Verse text came straight from holybible.ge to the browser, so
 * a slow or unreachable third party was a slow or unreachable service, live,
 * with no way to intervene. Responses are immutable — chapter 3 of John does
 * not change — so they cache well, and a cached chapter keeps working when the
 * origin does not.
 */

/** Room names are generated by the client; anything else is a typo or a probe. */
const ROOM_PATTERN = /^[a-z0-9]{8,64}$/;

/** A slide with three translations is a few kB. This is room to spare. */
const MAX_MESSAGE_BYTES = 256 * 1024;

/**
 * What each socket is, so the console can show whether the projector and OBS
 * are actually connected. Kept as a hibernation tag: tags survive the object
 * being evicted, which a field on `this` would not.
 */
const ROLES = ['console', 'show', 'lower3rd'];

/**
 * A socket that vanishes — a tab navigating away, OBS quitting, a phone losing
 * signal — never sends a close frame, so the room would go on reporting it as
 * connected. Clients therefore ping, and a socket that has not been heard from
 * within this window is treated as gone. Two missed pings are tolerated so a
 * brief stall does not blink the panel.
 */
const PING_STALE_MS = 70000;

/** How often the room prunes the dead and republishes who is present. */
const SWEEP_MS = 30000;

const UPSTREAM = 'https://holybible.ge/service.php';

/** Scripture does not change; a day is short only because the API might. */
const CACHE_SECONDS = 86400;

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Max-Age': '86400',
};

export class Room {
  constructor(state) {
    this.state = state;

    // Answered by the runtime without waking the object, so liveness costs
    // neither a request nor duration. The timestamp of the last auto-reply is
    // what `alive` reads.
    this.state.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping', 'pong'));
  }

  /** Has this socket been heard from recently enough to believe in? */
  alive(ws) {
    if (ws.readyState !== WebSocket.READY_STATE_OPEN) {
      return false;
    }

    const pong = this.state.getWebSocketAutoResponseTimestamp(ws);

    if (pong) {
      return Date.now() - pong.getTime() < PING_STALE_MS;
    }

    // Nothing heard yet: a socket is given one window to send its first ping.
    const { joined = 0 } = ws.deserializeAttachment() || {};

    return Date.now() - joined < PING_STALE_MS;
  }

  /**
   * Who is in the room, sent on every join and leave.
   *
   * A socket that has just closed can still be listed for a moment, so the
   * count is taken from those actually open — otherwise a projector that
   * navigates away is counted again by the very next join and appears
   * connected when it is gone. `except` drops the socket whose close handler
   * is running, which may not have changed state yet either.
   */
  announce(except = null) {
    const sockets = this.state.getWebSockets().filter(ws => ws !== except && this.alive(ws));

    const roles = ROLES.reduce((acc, role) => {
      acc[role] = sockets.filter(ws => this.state.getTags(ws).includes(role)).length;
      return acc;
    }, {});

    const message = JSON.stringify({ type: 'presence', roles });

    for (const ws of sockets) {
      try {
        ws.send(message);
      } catch (e) {
        // A peer closing mid-announce must not stop the rest.
      }
    }
  }

  async fetch(request) {
    if (request.headers.get('Upgrade') !== 'websocket') {
      return new Response('expected a websocket upgrade', { status: 426 });
    }

    const role = new URL(request.url).searchParams.get('role');
    const [client, server] = Object.values(new WebSocketPair());

    // The hibernation API rather than `server.accept()`: a room sits idle
    // between slides, and hibernating sockets are not billed for duration.
    this.state.acceptWebSocket(server, ROLES.includes(role) ? [role] : []);
    server.serializeAttachment({ joined: Date.now() });

    // The sweep runs only while the room is occupied.
    if ((await this.state.storage.getAlarm()) === null) {
      await this.state.storage.setAlarm(Date.now() + SWEEP_MS);
    }

    const last = await this.state.storage.get('last');

    if (last) {
      try {
        server.send(last);
      } catch (e) {
        // The socket died between accept and replay.
      }
    }

    this.announce();

    return new Response(null, { status: 101, webSocket: client });
  }

  async webSocketMessage(sender, message) {
    if (typeof message !== 'string' || message.length > MAX_MESSAGE_BYTES) {
      return;
    }

    // Only a slide is worth keeping and passing on. Anything else — a stray
    // keepalive, a client from a future version — must not become the payload
    // replayed to everything that joins next.
    try {
      if (!JSON.parse(message)?.showData) {
        return;
      }
    } catch (e) {
      return;
    }

    await this.state.storage.put('last', message);

    // Everyone but the sender: the console already knows what it just pushed,
    // and echoing would fight its own local state.
    for (const peer of this.state.getWebSockets()) {
      if (peer !== sender) {
        try {
          peer.send(message);
        } catch (e) {
          // A peer closing mid-broadcast must not stop the rest.
        }
      }
    }
  }

  async webSocketClose(ws) {
    try {
      ws.close(1000);
    } catch (e) {
      // Already gone.
    }

    this.announce(ws);
  }

  async webSocketError(ws) {
    this.announce(ws);
  }

  /**
   * Drops sockets nothing has been heard from and republishes the room. This
   * is what makes OBS quitting show up in the console, since a process that
   * dies sends no close frame.
   */
  async alarm() {
    for (const ws of this.state.getWebSockets()) {
      if (!this.alive(ws)) {
        try {
          ws.close(1001, 'no keepalive');
        } catch (e) {
          // Already gone.
        }
      }
    }

    this.announce();

    if (this.state.getWebSockets().length > 0) {
      await this.state.storage.setAlarm(Date.now() + SWEEP_MS);
    }
  }
}

/**
 * The API this proxies answers with `Cache-Control: no-cache`, so the response
 * is re-headered on the way into the cache. `Age` tells the client — and me,
 * when testing — whether an answer was served from Cloudflare or fetched.
 */
const proxyBible = async (request, ctx) => {
  const incoming = new URL(request.url);
  const upstream = new URL(UPSTREAM);

  for (const [key, value] of incoming.searchParams) {
    upstream.searchParams.set(key, value);
  }

  // The cache is keyed on the upstream URL, so every console asking for the
  // same chapter in the same translation shares one entry.
  const key = new Request(upstream.toString(), { method: 'GET' });
  const cache = caches.default;

  const hit = await cache.match(key);

  if (hit) {
    const response = new Response(hit.body, hit);
    response.headers.set('x-relay-cache', 'HIT');

    return response;
  }

  let upstreamResponse;

  try {
    upstreamResponse = await fetch(key, { headers: { accept: 'application/json, text/plain, */*' } });
  } catch (e) {
    return new Response(JSON.stringify({ error: 'upstream unreachable' }), {
      status: 502,
      headers: { ...CORS, 'content-type': 'application/json', 'x-relay-cache': 'ERROR' },
    });
  }

  const body = await upstreamResponse.arrayBuffer();

  const response = new Response(body, {
    status: upstreamResponse.status,
    headers: {
      ...CORS,
      'content-type': upstreamResponse.headers.get('content-type') || 'application/json',
      'cache-control': `public, max-age=${CACHE_SECONDS}`,
      'x-relay-cache': 'MISS',
    },
  });

  // Only success is worth keeping: caching an error would pin the outage in
  // place for a day, which is the opposite of the point.
  if (upstreamResponse.ok) {
    ctx.waitUntil(cache.put(key, response.clone()));
  }

  return response;
};

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS });
    }

    if (url.pathname === '/health') {
      return new Response('ok', { headers: { 'content-type': 'text/plain', ...CORS } });
    }

    if (url.pathname === '/bible') {
      return proxyBible(request, ctx);
    }

    const room = url.pathname.replace(/^\/+/, '');

    if (!ROOM_PATTERN.test(room)) {
      return new Response('room must be 8-64 characters of a-z0-9', { status: 400 });
    }

    return env.ROOMS.get(env.ROOMS.idFromName(room)).fetch(request);
  },
};
